<a href="https://colab.research.google.com/github/MKhromina/test_task/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_2(%D0%BB%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D1%8F).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Упражнение 1

In [ ]:
# подключение библиотек
from google.colab import files
import numpy as np
import pandas as pd

In [ ]:
data = pd.DataFrame(
{ "X" : [6,3,10,4,2,11,23,21,20,14], "Y" : [19,11,24,14,7,26,62,47,48,27]})
# X Количество человек в очереди, 
# Y Время, проведенное в очереди (мин).

результаты наблюдений длительности нахождения человека в очереди в зависимости от количества людей в этой очереди

In [ ]:
data

X   Y
0   6  19
1   3  11
2  10  24
3   4  14
4   2   7
5  11  26
6  23  62
7  21  47
8  20  48
9  14  27

Обучите модель линейной регрессии для прогнозирования и введите указанные параметры.

Определите выборочное среднее X

In [ ]:
data['X'].mean()

11.4

Определите выборочное среднее  Y

In [ ]:
data['Y'].mean()

28.5

моя функция

In [ ]:
def linreg (x, y):
  sum1=0
  sum2=0
  a=0
  b=0
  for i in range(len(x)):
    sum1+=(x[i]-x.mean())*(y[i]-y.mean())
    sum2+=(x[i]-x.mean())**2
  b1=sum1/sum2
  b0=y.mean()-x.mean()*b1

  # оценка точности R²
  for i in range(len(y)):
      a+=(y[i]-b0-b1*x[i])**2
      b+=(y[i]-y.mean())**2
  R=1-a/b
  
  print('b0 = ', b0)
  print('b1 = ', b1)
  print('R^2 = ', R)
  return 




In [ ]:
Y1=np.array([19, 11, 24, 14,  7, 26, 62, 47, 48, 27])


In [ ]:
X1=np.array([6,  3, 10,  4,  2, 11, 23, 21, 20, 14])

In [ ]:
linreg (X1,Y1)

b0 =  2.8066618392469245
b1 =  2.2538015930485154
R^2 =  0.953605092046016


конец моей функции

In [ ]:
#подключаем модель линейной регрессии из библиотеки sklearn
from sklearn.linear_model import LinearRegression
X=np.array(data['X']).reshape((-1, 1)) #потому что этот массив должен быть двумерным или более точным – иметь одну колонку и необходимое количество рядов
Y= np.array(data['Y'])

In [ ]:
model = LinearRegression() # Эта операция создаёт переменную model в качестве экземпляра LinearRegression

In [ ]:
model.fit(X, Y) # С помощью .fit() вычисляются оптимальные значение весов b₀ и b₁, используя существующие вход и выход (x и y) в качестве аргументов.

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

model содержит атрибуты .intercept_, который представляет собой коэффициент b₀ и .coef_, который представляет b₁

In [ ]:
model.coef_ # b₁

array([2.25380159])

In [ ]:
model.intercept_ # b₀

2.8066618392469174

Оцените точность модели, вычислив R²

In [ ]:
model.score(X, Y)

0.953605092046016

# Задание 2

В прилагаемом файле представлены данные, собранные путем голосования за самые лучшие (или, по крайней мере, самые популярные) конфеты Хэллоуина. Обучите модель линейной многомерной регрессии. В качестве предикторов выступают поля: chocolate, fruity, caramel, peanutyalmondy, nougat, crispedricewafer, hard, bar, pluribus, sugarpercent, pricepercent, отклик — winpercent.
В качестве тренировочного набора данных используйте данные из файла, за иключением следующих конфет: Chiclets, Fruit Chews. 

In [ ]:
data2=files.upload()
data2 = pd.read_csv("Практика_2.2.csv", index_col='competitorname')

Saving Практика_2.2.csv to Практика_2.2.csv


In [ ]:
#обучение модели будем проводить на данных, за исключением некоторых конфет
train_data = data2.drop(['Chiclets','Fruit Chews'])


In [ ]:
#отбираем данные для предикторов, удаляя два последних столбца, индекс не включается в данные.
xz2 = pd.DataFrame(train_data.drop(['winpercent', 'Y'], axis=1))


In [ ]:
#указываем столбец отклика
yz2 = pd.DataFrame(train_data['winpercent'])

In [ ]:
#подключаем модель линейной регрессии из библиотеки sklearn
from sklearn.linear_model import LinearRegression

In [ ]:
#обучение модели
reg = LinearRegression().fit(xz2, yz2)

предсказанное значение winpercent для конфеты с параметрами:

In [ ]:
#предсказание для конфет введеных вручную
reg.predict([[0, 0, 1, 0, 1, 0, 1, 0, 1, 0.607, 0.254]])

array([[30.72196705]])

предсказанное значение winpercent для конфеты Chiclets:

In [ ]:
#предсказание для конфет из таблицы

#выбираем строку из таблицы
Chiclets = data2.loc['Chiclets',:].to_frame().T

#отбираем данные для предикторов и выполняем предсказание с помощью модели
reg.predict(Chiclets.drop(['winpercent', 'Y'], axis=1))

array([[42.86644948]])

In [ ]:
Fruit_Chews = data2.loc['Fruit Chews',:].to_frame().T
reg.predict(Fruit_Chews.drop(['winpercent', 'Y'], axis=1))

array([[46.30862479]])

Значение коэффициента  θ0 :

In [ ]:
reg.intercept_

array([36.65129553])

Значение коэффициентов  θ1,...,θp

In [ ]:
reg.coef_

array([[25.77472951, 11.87480205, -1.82816139,  8.17152108,  3.76017256,
        10.26127488, -8.2332688 , -4.98407556, -3.12430336,  9.59234636,
        -9.15874697]])

In [ ]:
def linregpoi (x, y):
  B = np.dot(np.dot(np.linalg.inv(np.dot(x.transpose(),x)),x.transpose()),y) #
  return (B)

In [ ]:
def linregpoi2 (x, y):
  B = np.matmul(np.matmul(np.linalg.inv(np.matmul(x.transpose(),x)),x.transpose()),y)

  return (B)

In [ ]:
def linregpoi3 (x, y):
  A = np.matmul(x.transpose(), x)
  B = np.linalg.inv(A)
  C = np.matmul(B, x.transpose())
  D = np.matmul(C,y) #numpy.matmul¶

  return (D)

In [ ]:
xz3 = np.array(pd.concat([pd.Series(), xz2], axis = 1).fillna(1))
yz3 = np.array(yz2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """Entry point for launching an IPython kernel.


In [ ]:
linregpoi2(np.array(xz3), np.array(yz3))

array([[36.65129553],
       [25.77472951],
       [11.87480205],
       [-1.82816139],
       [ 8.17152108],
       [ 3.76017256],
       [10.26127488],
       [-8.2332688 ],
       [-4.98407556],
       [-3.12430336],
       [ 9.59234636],
       [-9.15874697]])