<a href="https://colab.research.google.com/github/MKhromina/test_task/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_5(%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#импорт необходимых библиотек
from google.colab import files
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

In [ ]:
data=files.upload() #загрузка данных (используется только для Google Colab)



Saving Практика_5.csv to Практика_5 (1).csv


In [ ]:
df = pd.read_csv('Практика_5.csv')

In [ ]:
df

Object   X   Y  Cluster
0        1   2  13        0
1        2   5   6        1
2        3  17   7        2
3        4   5  10        1
4        5  12   6        2
5        6  18   4        0
6        7  17   1        1
7        8   3  14        0
8        9  13   4        1
9       10  12  10        1
10      11  10   6        1
11      12   7   2        2
12      13  11   4        0
13      14  13  17        1
14      15   9   3        1

In [ ]:
x = df.iloc[:,1:-1]#выбор признаков
y = df.iloc[:,[-1]]#выбор значений

In [ ]:
Y=np.array(y)

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances

При выполнении задания с помощью библиотеки sklearn используйте начальную инициализацию со следующими координатами центроидов и параметрами:
KMeans(n_clusters=3, init=np.array([[8.5, 8.75], [10.5, 7.13], [12.0, 5.0]]), max_iter=100, n_init=1)

Укажите, к какому кластеру будет отнесен тот или иной объект в результате кластеризации.

In [ ]:
kmeans = KMeans(
    n_clusters=3,
    init=np.array([[8.5, 8.75], [10.5, 7.13], [12.0, 5.0]]),
    max_iter=100,
    n_init=1 )

In [ ]:
 kmeans.fit(np.array(x),np.array(y))

KMeans(algorithm='auto', copy_x=True,
       init=array([[ 8.5 ,  8.75],
       [10.5 ,  7.13],
       [12.  ,  5.  ]]),
       max_iter=100, n_clusters=3, n_init=1, n_jobs=None,
       precompute_distances='auto', random_state=None, tol=0.0001, verbose=0)

In [ ]:
kmeans.labels_ #вывод назначенных кластеров

array([0, 0, 2, 0, 1, 2, 2, 0, 2, 1, 1, 2, 2, 0, 2], dtype=int32)

In [ ]:
alldistances = kmeans.fit_transform(x)

In [ ]:
alldistances

array([[ 3.73630834, 10.9188929 , 14.59661689],
       [ 6.02992537,  6.47216261,  8.49729849],
       [12.44829306,  5.67646212,  5.16068339],
       [ 2.0880613 ,  6.87184271, 10.3746158 ],
       [ 8.77268488,  1.49071198,  2.68404203],
       [14.7566934 ,  7.45355992,  4.87601376],
       [15.84171708,  8.49836586,  4.63570878],
       [ 3.28024389, 10.67187373, 14.54759956],
       [10.89770618,  3.72677996,  0.45175395],
       [ 6.70522185,  2.74873708,  6.5293685 ],
       [ 7.4404301 ,  1.88561808,  3.97183965],
       [10.09752445,  6.87184271,  6.34066886],
       [ 9.65194281,  3.34995854,  2.18529408],
       [ 8.93084542,  9.80929265, 13.42933129],
       [ 9.62081078,  4.92160769,  4.18208033]])

In [ ]:
 kmeans.fit_predict(x)

array([0, 0, 2, 0, 1, 2, 2, 0, 2, 1, 1, 2, 2, 0, 2], dtype=int32)

По результатам выполнения кластеризации определить среднее расстояний между объектами и центроидом, отнесенных к кластеру 0

In [ ]:
sum=0
count=0
k=0
for i in kmeans.fit_predict(x):
  if i == 0:
    sum+=alldistances[k][0]
    count+=1
  k+=1
print(sum/count)
    


4.813076866197264
