<a href="https://colab.research.google.com/github/MKhromina/test_task/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Таблица некоторых синтетических данных, на основании которых необходимо выполнить классификацию нового объекта, с помощью метода -ближайших соседей

In [ ]:
# подключение библиотек
from google.colab import files
import numpy as np
import pandas as pd

In [ ]:
data = pd.DataFrame({ 'X' : [39,68, 58, 15, 13, 16, 48, 21, 66, 61], 'Y' : [23, 16, 42, 55, 49, 18, 84, 30, 95, 45], 'Class' : [1, 0, 1, 0, 0, 0, 0, 1, 0, 1] })

In [ ]:
data

X   Y  Class
0  39  23      1
1  68  16      0
2  58  42      1
3  15  55      0
4  13  49      0
5  16  18      0
6  48  84      0
7  21  30      1
8  66  95      0
9  61  45      1

Введите расстояние от нового объекта с координатами  до ближайшего соседа(67, 43), используя евклидову метрику.

Введите идентификатры трех ближайших точек к  для евклидовой метрики.

Введите класс для нового объекта с координатами  при  k=3 евклидовой метрике.

Введите расстояние от нового объекта с координатами  до ближайшего соседа, используя метрику городских кварталов (Манхеттенское расстояние).

Введите идентификатры трех ближайших точек к  для метрики городских кварталов

Введите класс для нового объекта с координатами  при  и метрике городских кварталов.

In [ ]:
A=[67, 43]
evkl=[]
monh=[]
for i in range(len(data.X)):
  evkl.append(((data.X[i]-A[0])**2+(data.Y[i]-A[1])**2)**(1/2))
  monh.append(abs(data.X[i]-A[0])+abs((data.Y[i]-A[1])))

print(evkl)
print(monh)

[34.40930106817051, 27.018512172212592, 9.055385138137417, 53.36665625650534, 54.3323108288245, 56.79788728465171, 45.18849411078001, 47.80167361086848, 52.009614495783374, 6.324555320336759]
[48, 28, 10, 64, 60, 76, 60, 59, 53, 8]


Методом из библиотеки

In [ ]:
X = pd.DataFrame(data.drop(['Class'], axis=1)) # Отбор данных для предикторов, удаление столбца Class
y = pd.DataFrame(data['Class']).values.ravel() # Отбор столбца Class для отклика

Подключение библиотеки и задание параметров модели: n_neighbors — число соседей; p — используемое расстояние. Манхэттенское расстояние — p=1, евклидово расстояние — p=2. Дополнительные параметры 

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3, p=2)
neigh.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

Назначенный класс:

In [ ]:
neigh.predict([A])

array([1])

Вероятности отнесения к классам 0 и 1 соответственно

In [ ]:
neigh.predict_proba([A])

array([[0.33333333, 0.66666667]])

Вывод расстояний до  k  соседей в порядке удаления (первый массив — расстояния, второй — идентификаторы объектов). Обращаем внимание, что метод возвращает индексы ближайших соседей с нуля, что не соответствует индексации в таблице.

In [ ]:
neigh.kneighbors([A])

(array([[ 6.32455532,  9.05538514, 27.01851217]]), array([[9, 2, 1]]))